// Development fixtures: names and instructions are distinct; images are labelled illustrations.
module.exports = [
  { name: 'Cơm chiên trứng', category: 'Cơm', prep: 10, cook: 10,
    ingredients: [['Cơm nguội', 400, 'g'], ['Trứng gà', 2, 'quả'], ['Hành lá', 20, 'g'], ['Dầu ăn', 15, 'ml']],
    steps: ['Đánh tan trứng, cắt nhỏ hành lá và đánh tơi cơm nguội.', 'Làm nóng dầu, cho trứng vào đảo chín rồi thêm cơm, đảo đều 7 phút.', 'Cho hành lá vào, đảo thêm một phút và chia cơm ra đĩa.'] },
  { name: 'Canh bí đỏ đậu phụ', category: 'Canh', prep: 10, cook: 20,
    ingredients: [['Bí đỏ', 300, 'g'], ['Đậu phụ', 200, 'g'], ['Nước', 700, 'ml'], ['Muối', 3, 'g']],
    steps: ['Gọt vỏ bí đỏ, bỏ hạt và cắt miếng; cắt đậu phụ thành khối.', 'Đun nước sôi, thêm bí đỏ và nấu nhỏ lửa đến khi mềm.', 'Cho đậu phụ và muối vào, đun nhẹ thêm 5 phút rồi múc ra bát.'] },
  { name: 'Đậu phụ sốt cà chua', category: 'Món chay', prep: 10, cook: 15,
    ingredients: [['Đậu phụ', 300, 'g'], ['Cà chua', 250, 'g'], ['Dầu ăn', 20, 'ml'], ['Muối', 3, 'g']],
    steps: ['Cắt đậu phụ thành miếng vừa ăn, thái nhỏ cà chua.', 'Áp chảo đậu phụ với dầu cho vàng hai mặt rồi gắp ra.', 'Nấu cà chua với chút nước thành sốt, thêm muối và đậu phụ, om 5 phút.'] },
  { name: 'Rau muống xào tỏi', category: 'Món xào', prep: 10, cook: 5,
    ingredients: [['Rau muống', 400, 'g'], ['Tỏi', 15, 'g'], ['Dầu ăn', 15, 'ml'], ['Muối', 3, 'g']],
    steps: ['Nhặt rau muống, rửa sạch và để ráo; bóc tỏi, đập dập.', 'Làm nóng dầu, phi tỏi thơm rồi thêm rau muống, đảo trên lửa lớn.', 'Thêm muối và đảo đến khi rau chín, bày ra đĩa dùng ngay.'] },
  { name: 'Khoai lang hấp', category: 'Món hấp', prep: 5, cook: 25,
    ingredients: [['Khoai lang', 500, 'g'], ['Nước', 1000, 'ml']],
    steps: ['Chà rửa khoai lang, cắt bỏ hai đầu và phần bị hỏng.', 'Đun nước trong nồi hấp rồi xếp khoai lên xửng, đậy nắp.', 'Hấp khoảng 25 phút; kiểm tra khoai mềm bằng đũa trước khi lấy ra.'] },
  { name: 'Salad dưa chuột cà chua', category: 'Salad', prep: 15, cook: 0,
    ingredients: [['Dưa chuột', 250, 'g'], ['Cà chua', 200, 'g'], ['Dầu ô liu', 10, 'ml'], ['Nước cốt chanh', 10, 'ml']],
    steps: ['Rửa sạch dưa chuột, cà chua và để ráo trước khi thái miếng.', 'Khuấy đều dầu ô liu với nước cốt chanh để làm sốt.', 'Trộn rau củ với sốt nhẹ tay, chia ra bát và dùng ngay.'] },
  { name: 'Cháo nấm cà rốt', category: 'Cháo', prep: 10, cook: 35,
    ingredients: [['Gạo tẻ', 100, 'g'], ['Nấm hương tươi', 100, 'g'], ['Cà rốt', 100, 'g'], ['Nước', 1000, 'ml'], ['Muối', 3, 'g']],
    steps: ['Vo gạo, rửa nấm và thái nhỏ; gọt cà rốt rồi cắt hạt lựu.', 'Đun gạo với nước nhỏ lửa 25 phút, khuấy để không bén đáy.', 'Cho cà rốt, nấm và muối vào; nấu thêm 10 phút đến khi chín mềm.'] },
  { name: 'Mì xào nấm', category: 'Mì và bún', prep: 10, cook: 10,
    ingredients: [['Mì trứng khô', 150, 'g'], ['Nấm hương tươi', 150, 'g'], ['Cà rốt', 100, 'g'], ['Dầu ăn', 15, 'ml'], ['Nước tương', 15, 'ml']],
    steps: ['Luộc mì theo hướng dẫn trên bao bì, để ráo; thái nấm và cà rốt.', 'Làm nóng dầu, xào cà rốt và nấm đến khi chín.', 'Thêm mì cùng nước tương, đảo đều 2 phút rồi bày ra đĩa.'] },
  { name: 'Bánh mì trứng áp chảo', category: 'Bữa sáng', prep: 5, cook: 5,
    ingredients: [['Bánh mì', 2, 'ổ'], ['Trứng gà', 2, 'quả'], ['Dưa chuột', 100, 'g'], ['Dầu ăn', 10, 'ml']],
    steps: ['Rửa và thái lát dưa chuột, rạch bánh mì theo chiều dọc.', 'Làm nóng dầu, đập trứng vào chảo và nấu đến độ chín mong muốn.', 'Cho trứng và dưa chuột vào bánh mì, dùng khi còn ấm.'] },
  { name: 'Sữa chua chuối yến mạch', category: 'Ăn nhẹ', prep: 5, cook: 0,
    ingredients: [['Sữa chua', 200, 'g'], ['Chuối', 2, 'quả'], ['Yến mạch ăn liền', 40, 'g']],
    steps: ['Bóc vỏ chuối và cắt thành khoanh vừa ăn.', 'Chia sữa chua vào hai bát, trộn với yến mạch ăn liền.', 'Xếp chuối lên trên, để yến mạch mềm vài phút rồi thưởng thức.'] },
];
