const existingFiles = [
  'avtComChienTrung.jpg',
  'avtCanhBiDoDauPhu.jpg',
  'avt-dau-sot-ca-chua.jpg',
  'avtRauMuongXaoToi.jpg',
  'avtKhoaiLangHap.jpg',
  'avtSaladCaChuaDuaChuot.jpg',
  'avtChaoNamCaRot.jpg',
  'avt-mi-xao-nam.jpg',
  'avtbanhMiTrungApChao.jpg',
  'avtsuachuachuoiyenmach.jpg',
];

const imageOverrides = {
  11: { generalSearch: true, candidateOffset: 4 },
  20: {
    directImage: 'https://cdn-i.vtcnews.vn/resize/th/upload/2023/09/22/banana-oatmeal-b38b2229d8a7447094f7eca0cbafb908-16565521.jpg',
    directSource: 'https://vtcnews.vn/',
  },
  24: {
    directImage: 'https://cdn.tgdd.vn/2021/11/CookRecipe/Avatar/ca-rot-nuong-mat-ong-thumbnail.jpg',
    directSource: 'https://www.dienmayxanh.com/vao-bep/',
  },
  28: { generalSearch: true, candidateOffset: 0 },
  29: { generalSearch: true, candidateOffset: 0 },
  35: {
    directImage: 'https://amthucdochay.com/wp-content/uploads/2021/05/sup-ngo-5.jpg',
    directSource: 'https://amthucdochay.com/sup-ngo-chay/',
  },
  37: {
    directImage: 'https://file.hstatic.net/200000700229/file/ga-kho-hanh-phi-va-hanh-la-06.jpg',
    directSource: 'https://www.bluestone.com.vn/blogs/vao-bep/ga-kho-hanh-phi-va-hanh-la',
  },
  40: {
    directImage: 'https://barona.vn/storage/meo-vat/54/ga-nuong-sa-ot.jpg',
    directSource: 'https://barona.vn/cach-lam-ga-nuong-sa-ot',
  },
  44: {
    directImage: 'https://monngonmoingay.com/wp-content/uploads/2025/01/26.-SALAD-TAO-PHO-MAI.png',
    directSource: 'https://monngonmoingay.com/salad-tao-pho-mai/',
  },
  53: { generalSearch: true, candidateOffset: 0 },
  55: {
    directImage: 'https://cdn.tgdd.vn/News/Thumb/1468873/co-nen-an-sua-chua-voi-mat-ong-khong-thumb-1-1200x628.jpg',
    directSource: 'https://www.dienmayxanh.com/kinh-nghiem-hay/',
  },
};

module.exports = [
  ['Cơm chiên trứng', 'egg fried rice'],
  ['Canh bí đỏ đậu phụ', 'pumpkin tofu soup'],
  ['Đậu phụ sốt cà chua', 'tofu tomato sauce'],
  ['Rau muống xào tỏi', 'stir fried water spinach garlic'],
  ['Khoai lang hấp', 'steamed sweet potato'],
  ['Salad dưa chuột cà chua', 'cucumber tomato salad'],
  ['Cháo nấm cà rốt', 'mushroom rice porridge carrot'],
  ['Mì xào nấm', 'stir fried noodles mushroom'],
  ['Bánh mì trứng áp chảo', 'Vietnamese egg banh mi'],
  ['Sữa chua chuối yến mạch', 'banana oatmeal yogurt bowl'],
  ['Cơm gạo lứt ức gà · 01', 'brown rice grilled chicken breast bowl'],
  ['Cá hồi áp chảo · 02', 'pan seared salmon plate'],
  ['Bò xào ớt chuông · 03', 'beef bell pepper stir fry'],
  ['Heo nạc kho gừng · 04', 'Vietnamese ginger braised pork'],
  ['Trứng cuộn rau củ · 05', 'vegetable rolled omelette'],
  ['Đậu hũ sốt cà · 06', 'fried tofu tomato sauce'],
  ['Cháo đậu xanh · 07', 'mung bean rice porridge'],
  ['Salad đậu đỏ · 08', 'red bean salad'],
  ['Chè đậu đen ít ngọt · 09', 'Vietnamese black bean sweet soup'],
  ['Yến mạch chuối · 10', 'banana oatmeal bowl'],
  ['Khoai lang nướng · 11', 'roasted sweet potato'],
  ['Súp khoai tây · 12', 'potato soup'],
  ['Canh bí đỏ · 13', 'pumpkin soup bowl'],
  ['Cà rốt hấp mật ong · 14', 'honey glazed steamed carrots'],
  ['Salad cà chua · 15', 'fresh tomato salad'],
  ['Bông cải xanh xào tỏi · 16', 'garlic broccoli stir fry'],
  ['Cải bó xôi trứng · 17', 'spinach scrambled eggs'],
  ['Cải thìa sốt nấm · 18', 'bok choy mushroom sauce'],
  ['Canh rau muống · 19', 'Vietnamese water spinach soup'],
  ['Xà lách cuộn thịt · 20', 'lettuce meat wraps'],
  ['Dưa leo trộn chua ngọt · 21', 'Asian sweet sour cucumber salad'],
  ['Ớt chuông nhồi thịt · 22', 'meat stuffed bell peppers'],
  ['Nấm hương kho tiêu · 23', 'braised shiitake mushrooms pepper'],
  ['Nấm đùi gà nướng · 24', 'grilled king oyster mushrooms'],
  ['Súp ngô ngọt · 25', 'sweet corn soup'],
  ['Hành tây xào bò · 26', 'beef onion stir fry'],
  ['Gà hành lá · 27', 'scallion chicken dish'],
  ['Tôm rang tỏi · 28', 'garlic shrimp skillet'],
  ['Cá hấp gừng · 29', 'steamed fish ginger scallion'],
  ['Gà nướng sả · 30', 'Vietnamese lemongrass grilled chicken'],
  ['Nước chanh hạt chia · 31', 'lemon chia seed drink'],
  ['Bánh mì bơ trứng · 32', 'avocado egg toast'],
  ['Sinh tố chuối · 33', 'banana smoothie glass'],
  ['Salad táo · 34', 'fresh apple salad'],
  ['Nước cam cà rốt · 35', 'orange carrot juice'],
  ['Sữa chua trái cây · 36', 'fruit yogurt bowl'],
  ['Súp sữa tươi bí đỏ · 37', 'creamy pumpkin soup'],
  ['Mì phô mai rau củ · 38', 'cheese vegetable noodles'],
  ['Pudding hạt chia · 39', 'chia seed pudding'],
  ['Gà hạt điều · 40', 'cashew chicken'],
  ['Yến mạch hạnh nhân · 41', 'almond oatmeal bowl'],
  ['Salad dầu ô liu · 42', 'Mediterranean salad olive oil'],
  ['Đậu hũ sốt nước tương · 43', 'tofu soy sauce dish'],
  ['Cá kho nước mắm · 44', 'Vietnamese braised fish clay pot'],
  ['Sữa chua mật ong · 45', 'honey yogurt bowl'],
  ['Bún gạo tôm · 46', 'shrimp rice vermicelli bowl'],
  ['Mì nguyên cám bò · 47', 'beef whole wheat noodles'],
  ['Tôm hấp sả · 48', 'Vietnamese steamed shrimp lemongrass'],
  ['Mực xào rau củ · 49', 'squid vegetable stir fry'],
  ['Cơm gia đình Cookmate · 50', 'Vietnamese family meal rice dishes'],
].map(([name, query], index) => ({
  index: index + 1,
  name,
  query,
  existingFilename: existingFiles[index],
  ...(imageOverrides[index + 1] || {}),
  filename: `recipe-${String(index + 1).padStart(3, '0')}.webp`,
  publicPath: `/uploads/mon-an/recipe-${String(index + 1).padStart(3, '0')}.webp`,
}));
