import { Platform, StyleSheet } from 'react-native'
export const colors = {
  background: '#fffaf6',
  card: '#ffffff',
  ink: '#422c21',
  muted: '#927f73',
  accent: '#bd420b',
  soft: '#fff0e7',
  border: '#f0e4da',
  green: '#6e8552',
  greenSoft: '#f0f5e8',
  red: '#af3832',
}
export const headingFont = Platform.select({
  ios: 'System',
  android: 'sans-serif',
  default: 'system-ui',
})
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background },
  content: { padding: 22, paddingBottom: 30 },
  row: { flexDirection: 'row', alignItems: 'center' },
  between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  title: { fontSize: 30, fontWeight: '700', color: colors.ink, lineHeight: 39 },
  heading: { fontSize: 21, fontWeight: '700', color: colors.ink },
  serif: { fontFamily: headingFont },
  body: { fontSize: 14, lineHeight: 22, color: colors.ink },
  muted: { fontSize: 13, lineHeight: 21, color: colors.muted },
  small: { fontSize: 11, color: colors.muted, lineHeight: 18 },
  card: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
  },
  section: { marginTop: 26, marginBottom: 16 },
  label: { fontSize: 13, fontWeight: '600', color: colors.ink, marginBottom: 8 },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: '#fff',
    padding: 14,
    fontSize: 14,
    color: colors.ink,
    minHeight: 50,
  },
  field: { marginBottom: 18 },
  badge: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '600',
    backgroundColor: colors.soft,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: 18 },
  link: { color: colors.accent, fontSize: 12, fontWeight: '600' },
  empty: { padding: 30, alignItems: 'center', gap: 12 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 24,
    backgroundColor: '#fff',
    marginRight: 9,
  },
  chipActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  chipText: { fontSize: 12, color: colors.muted },
  chipTextActive: { color: '#fff', fontWeight: '600' },
})
